### ISSUE TITLE
unable to run task!

### ISSUE THREAD

**Issue by luistrong** [baker221/alfred-clipboard-ocr-youdao#1]
![image](https://user-images.githubusercontent.com/49417688/140461981-101163f5-f401-47f2-92be-147a881cd009.png)

问题出在哪?

**Comment by baker221** [comment]
抱歉，在提交的时候没有针对环境做优化。

请您双击整个流程的 `Run Script` 块，将第 1 行从
```
#!/usr/local/anaconda3/envs/alfred/bin/python3
```

改为
```
#!python3
```

来尝试是否生效。

**Comment by luistrong** [comment]
> 抱歉，在提交的时候没有针对环境做优化。
> 
> 请您双击整个流程的 `Run Script` 块，将第 1 行从
> 
> ```
> #!/usr/local/anaconda3/envs/alfred/bin/python3
> ```
> 
> 改为
> 
> ```
> #!python3
> ```
> 
> 来尝试是否生效。

改了, 还是出现一样的提示
![image](https://user-images.githubusercontent.com/49417688/140468045-719fc6fa-04bf-411a-bb5d-b9b2485c3e46.png)

**Comment by baker221** [comment]
点击此处后，在文件的位置打开终端。

![image](https://user-images.githubusercontent.com/43471538/140468286-b0d059ef-8a32-4fda-bc04-bab52feabcfa.png)

运行 `chmod +x main.py`。

如果还有问题，点击此处后再运行 workflow。

![image](https://user-images.githubusercontent.com/43471538/140468434-f8d4c564-61bb-4288-b853-42291a797128.png)

然后将错误信息贴出。

**Comment by luistrong** [comment]
"在文件的位置打开终端"是指在文件夹那个界面运行终端命令吧? 显示找不到文件
![image](https://user-images.githubusercontent.com/49417688/140469718-8ba6faca-b50e-4f1d-a33e-bcdcb2c778ab.png)
![image](https://user-images.githubusercontent.com/49417688/140469734-4e4bd153-7b70-4264-bcb9-98276d7df55f.png)

**Comment by baker221** [comment]
> "在文件的位置打开终端"是指在文件夹那个界面运行终端命令吧? 显示找不到文件 ![image](https://user-images.githubusercontent.com/49417688/140469718-8ba6faca-b50e-4f1d-a33e-bcdcb2c778ab.png) ![image](https://user-images.githubusercontent.com/49417688/140469734-4e4bd153-7b70-4264-bcb9-98276d7df55f.png)

。。。您的终端没有跳转到对应的文件夹啊。。对着 `main.py` 在的文件夹右键，然后终端输入 `cd ` （注意有空格），然后粘贴刚刚复制的东西。

**Comment by baker221** [comment]
或者您对着那个文件夹右键，下面的服务里面有个选项 `新建在此文件夹的终端` ，然后再运行 `chmod`

**Comment by luistrong** [comment]
还是出现一样的提示, 不知道我哪里又弄的不对, 麻烦您了
![image](https://user-images.githubusercontent.com/49417688/140470908-b71e4e19-6266-453a-9ab7-622cdd263502.png)

**Comment by baker221** [comment]
> 还是出现一样的提示, 不知道我哪里又弄的不对, 麻烦您了
> ![image](https://user-images.githubusercontent.com/49417688/140470908-b71e4e19-6266-453a-9ab7-622cdd263502.png)

输入上面的 chmod 指令而不是只是 chmod

**Comment by luistrong** [comment]
> > 还是出现一样的提示, 不知道我哪里又弄的不对, 麻烦您了
> > ![image](https://user-images.githubusercontent.com/49417688/140470908-b71e4e19-6266-453a-9ab7-622cdd263502.png)
> 
> 输入上面的 chmod 指令而不是只是 chmod

还是不行哦...

**Comment by luistrong** [comment]
我知道了, 应该是我没安装Python3吧...
但以前原版的调用百度api的可以, 后来百度api不行了

**Comment by FrankZhang2000** [comment]
按理来说macos自带python3，终端里输which python3有反应就是有python3

**Comment by snow212-cn** [comment]
按楼上所有方法还是不行，不报错也没反应了，换回原版百度的正常使用
