### ISSUE TITLE
运行时出错，OS X 12.1 环境下。请帮看一下。

### ISSUE THREAD

**Issue by osaka2020** [baker221/alfred-clipboard-ocr-youdao#2]
出错。刚升级到了OS X 12.1，但是发现运行时出错。请帮看一下是什么问题呢。
<img width="296" alt="iShot2022-01-06 12 27 39" src="https://user-images.githubusercontent.com/93255760/148328858-e7e234a8-36cd-4701-ad44-921262219651.png">

**Comment by baker221** [comment]
初步看应该是 py 文件没有运行权限，您可以进入快捷指令所在的文件夹，运行 `chmod +x main.py` 来添加运行权限。（运行之前请注意把 py 文件第一行改成现在的版本）

**Comment by osaka2020** [comment]
@baker221 试了你给的赋权命令，第一行改为/usr/bin/python 还是不行啊。奇怪了。我是不懂编程的小白，请帮忙啊。谢谢

**Comment by baker221** [comment]
> @baker221 试了你给的赋权命令，第一行改为/usr/bin/python 还是不行啊。奇怪了。我是不懂编程的小白，请帮忙啊。谢谢

改成 /usr/bin/python3  如果还有问题，请再次截图错误信息

**Comment by osaka2020** [comment]
请帮看一下。而且发现出错一次后，再次运行就什么反应也没有了。
![iShot2022-01-17 13 32 11](https://user-images.githubusercontent.com/93255760/149713273-1a97ea87-b5cc-49a8-b411-d3ae3a950255.jpg)
![iShot2022-01-17 13 31 10](https://user-images.githubusercontent.com/93255760/149713279-34e7efe4-158e-4f64-928b-95a8a3eb7859.jpg)
![iShot2022-01-17 13 30 58](https://user-images.githubusercontent.com/93255760/149713291-2b86bb6d-2684-4403-b356-b7f179d70a38.jpg)

**Comment by phpluo** [comment]
遇到同样的问题，我在文件开头加了我的Python3的路径 终端执行`which python3` 然后调试的时候提示 缺少requests模块 然后终端执行`pip3 install requests` 后面就 可以运行起来了

**Comment by DottChen** [comment]
估计和 MacOS 升级后移除了 python2 有关系，把 `main.py` 的第一行改成自己 python 的路径就可以了。路径可以用 `which python3` 查看。
<img width="477" alt="image" src="https://user-images.githubusercontent.com/32103329/173231005-6c6c63a2-294a-4b99-80ae-bfb1d86eb10d.png">
